# Generated by Django 5.2 on 2025-04-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoraapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
